
GET  http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwMDEsIm5hbWUiOiJuYW5kYSIsImVtYWlsIjoibmFuZGFuYWRsaXJpbkBnbWFpbC5jb20iLCJpYXQiOjE2NjA0NTc2MjMsImV4cCI6MTY2MDQ1NzYzOH0.B2FgHrdkFIXJ04TDqq7X725d3ARt1Dz9aXofJJkzXXs

###
POST  http://localhost:5000/users
Content-Type: application/json


{
    "name": "nanda",
    "email": "nandanadlirin@gmail.com",
    "password": "123",
    "confPassword": "123"
}

###
POST  http://localhost:5000/login
Content-Type: application/json

{
    "email": "nandanadlirin@gmail.com",
    "password": "123"
}

###
GET  http://localhost:5000/token

###
DELETE http://localhost:5000/logut

###
GET  http://localhost:5000/search?page=&limit=10
