GET  http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsIm5hbWUiOiJuYW5kYXMiLCJlbWFpbCI6Im5hbmFkMTIyMTMxMmRuMjE5OUBnbWFpbC5jb20iLCJpYXQiOjE2NTc5ODA4MTgsImV4cCI6MTY1Nzk4MDgzM30.UumJAVdtIHqVwropGfKP-EqxKnG424K6ia2UIfs6eSI


###
POST  http://localhost:5000/users
Content-Type: application/json


{
    "name": "nandas",
    "email": "nanad1221312dn2199@gmail.com",
    "password": "12345678",
    "confPassword": "12345678"
}

###
POST  http://localhost:5000/login
Content-Type: application/json

{
    "email": "nanad1221312dn2199@gmail.com",
    "password": "12345678"
}

###
GET  http://localhost:5000/token

###
DELETE http://localhost:5000/logut